import BoardLayout from "@/components/layout/BoardLayout";
import Head from "next/head";
import styles from "@/styles/Board.module.css";

export default function Board(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <BoardLayout />
      </main>
    </>
  );
}
